# Generated by Django 5.0.12 on 2025-02-13 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airplane_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "max_passengers",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_capacity_multiplier", models.FloatField(default=200.0)),
                (
                    "log_base",
                    models.CharField(
                        choices=[
                            ("10", "Base 10"),
                            ("e", "Natural Logarithm"),
                        ],
                        default="10",
                        max_length=2,
                    ),
                ),
                ("passenger_fuel_impact", models.FloatField(default=0.002)),
                (
                    "fuel_consumption_coefficient",
                    models.FloatField(default=0.8),
                ),
                (
                    "time_unit",
                    models.CharField(
                        choices=[
                            ("minute", "Minute"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                        ],
                        default="minute",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="FuelCalculationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("passengers", models.PositiveIntegerField()),
                ("fuel_capacity", models.FloatField()),
                ("fuel_consumption_per_minute", models.FloatField()),
                ("flight_duration", models.FloatField()),
                ("time_unit", models.CharField(max_length=10)),
                ("configuration_snapshot", models.JSONField()),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.airplane",
                    ),
                ),
            ],
        ),
    ]
