name: tests

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["main"]
    paths:
      - "fuel_tracker/**"
      - "requirements/**"
      - "tests/**"
      - "compose/**"
      - "config/**"
      - "locale/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest-and-coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip test]')"

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f docker-compose.local.yml build django

      - name: Check DB Migrations
        run: docker compose -f docker-compose.local.yml run --rm django python manage.py makemigrations --check

      - name: Run DB Migrations
        run: docker compose -f docker-compose.local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker compose -f docker-compose.local.yml run django pytest

      - name: Check coverage
        run: docker compose -f docker-compose.local.yml run --rm django coverage html

      - name: Tear down the Stack
        run: docker compose -f docker-compose.local.yml down
